services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
      PGDATA: /var/lib/postgresql/18/docker
      INSERT_SEED: "${INSERT_SEED:-true}" # if set in enviroment use that value, else default to true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
